### PR TITLE
Added italian translation

### PR DESCRIPTION
**Pull request by mirkobrombin**

### CODE REVIEW

**Comment by lainsce** [comment]
Please add `it` to LINGUAS file.

**Comment by mirkobrombin** [comment]
https://github.com/lainsce/yishu/blob/e0e58e53927c15ddd20839d25c641145c9a730cd/po/LINGUAS#L78

https://github.com/lainsce/yishu/blob/e0e58e53927c15ddd20839d25c641145c9a730cd/po/extra/LINGUAS#L78

**Comment by mirkobrombin** [comment]
https://github.com/lainsce/yishu/blob/e0e58e53927c15ddd20839d25c641145c9a730cd/po/LINGUAS#L78
https://github.com/lainsce/yishu/blob/e0e58e53927c15ddd20839d25c641145c9a730cd/po/extra/LINGUAS#L78

**Comment by lainsce** [comment]
Sorry, I thought it wasn't there

**Pull request merged**
